// Type definition for project details
export type ProjectDetail = {
  id: number                // Unique identifier for the project
  title: string            // Project title
  company: string          // Company name
  overview: string         // Brief project overview
  mainImage: string        // Main project image path
  link: string            // Live project URL
  github?: string         // Optional GitHub repository URL
  features: {             // List of project features
    title: string         // Feature title
    description: string   // Feature description  
    image: string | string[] // Feature image(s) path
  }[]
  techStack: {            // Technical stack groupings
    category: string      // Tech category name
    items: string[]       // List of technologies
  }[]
  achievements: {         // Quantifiable achievements
    metric: string        // Achievement metric name
    value: string         // Achievement value
    change: number        // Numerical change/improvement
  }[]
}

// Project data mapping object
export const PROJECT_DATA: Record<number, ProjectDetail> = {
  1: {
    id: 1,
    title: "Sphere Manipulation with Acoustic Levitation",
    company: "The University of Tokyo",
    overview: "This project explores the use of acoustic radiation pressure generated by ultrasound to levitate and manipulate spherical objects.",
    mainImage: "/system.jpg",
    link: "https://drive.google.com/file/d/1LjO75Vi5ac0VqpbZLZvHeIUyRRAzamRs/view?usp=drive_link",
    features: [
      {
        title: "Feature 1",
        description: "",
        image: "/example1/feature1.png"
      }
    ],
    techStack: [
      {
        category: "Core Technologies",
        items: ["Python", "OpenCV", "AUTD3"]
      }
    ],
    achievements: [
      {
        metric: "",
        value: "",
        change: 50
      }
    ]
  },
  2: {
    id: 2,
    title: "Upcoming...",
    company: "",
    overview: "Stay tuned for updates!",
    mainImage: "",
    link: "",
    features: [
      {
        title: "",
        description: "",
        image: ""
      }
    ],
    techStack: [
      {
        category: "",
        items: []
      }
    ],
    achievements: [
      {
        metric: "",
        value: "",
        change: 95
      }
    ]
  }
}

// Helper function: Get project by ID
export const getProjectById = (id: number): ProjectDetail | undefined => {
  if (!Object.keys(PROJECT_DATA).length) {
    console.warn('PROJECT_DATA is empty');
    return undefined;
  }
  return PROJECT_DATA[id] || Object.values(PROJECT_DATA)[0];
}