'use client'

import Image from "next/image"
import AnimatedText from "../common/AnimatedText"

export default function About() { // TODO: Edit this section.
  const aboutPhotos = [
    {
      src: "/20230727.JPG",
      alt: "A candid moment during travel",
      className: "sm:col-span-2 sm:row-span-2"
    },
    {
      src: "/20250320.JPG",
      alt: "Portrait shot",
      className: "sm:col-span-1 sm:row-span-1"
    },
    {
      src: "/20250930.JPG",
      alt: "Outdoor scene",
      className: "sm:col-span-1 sm:row-span-1"
    }
  ]

  return (
    <section id="about" className="min-h-screen w-full flex items-center justify-center px-6 py-16 sm:px-10">
      <div className="w-full max-w-6xl space-y-12">
        <AnimatedText>
          <div className="space-y-4 text-center">
            <h1 className="inline-block text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-600 via-pink-600 to-purple-600 dark:from-purple-400 dark:via-pink-400 dark:to-purple-400 mb-8">About Me</h1>
            <p className="mx-auto max-w-3xl text-foreground/70 leading-relaxed">
              I was born in Chiba, Japan in 2002.
              <br />
              As an undergraduate, I majored in Fisheries Science at Hokkaido University. I was also fortunate to have the opportunity to study abroad in the United States, which broadened my horizons and provided me with valuable experience. While in the U.S., I traveled solo through Central and South America, which remains a highlight of my life.
              <br />
              When I entered graduate school at the University of Tokyo, I switched my focus to the field of information technology. Currently, I am working to expand the application of physical phenomena using ultrasound with the goal of realizing new user interfaces.
            </p>
          </div>
        </AnimatedText>

        <div className="grid grid-cols-1 gap-10 lg:grid-cols-5 lg:gap-12">
          <div className="space-y-8 lg:col-span-3">
            <AnimatedText>
              <div className="space-y-4">
                <h2 className="flex items-center gap-3 text-2xl font-semibold">
                  <span className="h-7 w-[4px] rounded-full bg-gradient-to-b from-purple-600 via-pink-600 to-purple-600 dark:from-purple-400 dark:via-pink-400 dark:to-purple-400" aria-hidden="true" />
                  Personal Interests
                </h2>
                <p className="text-lg text-foreground/80 leading-relaxed">
                  I find it exciting to grow as a person by learning new things in fields that interest me and taking on challenging tasks. I enjoy watching baseball through a scientific perspective, such as sabermetrics, as well as Japanese art forms like manga and anime, and exploring new places.
                </p>
              </div>
            </AnimatedText>

            <AnimatedText>
              <div className="space-y-4">
                <h2 className="flex items-center gap-3 text-2xl font-semibold">
                  <span className="h-7 w-[4px] rounded-full bg-gradient-to-b from-purple-600 via-pink-600 to-purple-600 dark:from-purple-400 dark:via-pink-400 dark:to-purple-400" aria-hidden="true" />
                  Research Field
                </h2>
                <p className="text-lg text-foreground/80 leading-relaxed">
                  Currently, I am working on a project that uses acoustic radiation pressure generated by ultrasound to levitate and manipulate objects, with the goal of applying this technology to areas such as tangible user interfaces and next-generation displays.
                </p>
              </div>
            </AnimatedText>
          </div>

          <AnimatedText className="lg:col-span-2">
            <div className="space-y-5">
              <div className="grid grid-cols-2 gap-3 sm:gap-4">
                {aboutPhotos.map((photo) => (
                  <div
                    key={photo.src}
                    className={`group relative overflow-hidden rounded-2xl border border-black/10 bg-black/[0.04] shadow-sm transition-transform duration-300 hover:-translate-y-1 hover:shadow-xl dark:border-white/15 dark:bg-white/[0.05] ${photo.className}`}
                  >
                    <div className="relative h-48 sm:h-56">
                      <Image
                        src={photo.src}
                        alt={photo.alt}
                        fill
                        sizes="(max-width: 640px) 50vw, (max-width: 1024px) 40vw, 28vw"
                        className="object-cover transition-transform duration-500 group-hover:scale-105"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </AnimatedText>
        </div>
      </div>
    </section>
  )
}